import IDataObject from "../general/IDataObject";
import uuid from "uuid-random";
import { PriceGroup } from "../general/PriceGroup";
import Balances from "./Balances";

//
export interface IAccount extends IDataObject {
    company: string;
    priceGroup: PriceGroup;
    accountCodeGuid: string;
    branchGuid: string;
    resellerGuid: string;
    defaultSalesPersonGuid: string;
    defaultDeliveryRouteGuid: string;
    defaultCustomerGuid: string;
    refId: string;
    firstName: string;
    lastName: string;
    shippingSameAsPost: boolean;
    shipStreet: string;
    shipState: string;
    shipCity: string;
    shipPostcode: string;
    shipCountry: string;
    postStreet: string;
    postState: string;
    postCity: string;
    postPostcode: string;
    postCountry: string;
    phone: string;
    fax: string;
    mobile: string;
    email: string;
    website: string;
    abn: string;
    remarks: string;
    adminNotes: string;
    statement: number;
    bankBsb: string;
    bankAccountNo: string;
    bankName: string;
    eftBankRef: string;
    lodgementRef: string;
    emails: string;
    phoneNumbers: string;
    addresses: string;
    externalRefId: string;

    discountDays: number;
    discountAmount: number;
    creditLimit: number;
    showRunningTotals: boolean;
    isReseller: boolean;
    showInPos: boolean;
    lockDebtor: boolean;
    lockDiscounts: boolean;
    orderOnMonday: boolean;
    orderOnTuesday: boolean;
    orderOnWednesday: boolean;
    orderOnThursday: boolean;
    orderOnFriday: boolean;
    orderOnSaturday: boolean;
    orderOnSunday: boolean;
    dropShipping: boolean;
    isSupplier: boolean;
    isCustomer: boolean;
    preventExport: boolean;
    syncCounter: boolean;
    discountSyncCounter: boolean;
    revision: string;
    modTime: string;

    //syncInvoicesToWeb: boolean;
    // isCasualContact: boolean;
    balances: Balances|null;
    extRefId: string;
    // userName: string;

    terms: string;
}

export default class Account implements IAccount {
    guid: string = '';
    company: string = '';
    priceGroup: PriceGroup = PriceGroup.Retail;
    accountCodeGuid: string = '';
    defaultCustomerGuid: string = '';
    branchGuid: string = '';
    resellerGuid: string = '';
    defaultSalesPersonGuid: string = '';
    defaultDeliveryRouteGuid: string = '';
    refId: string = '';
    firstName: string = '';
    lastName: string = '';
    shipStreet: string = '';
    shipCity: string = '';
    shipState: string = '';
    shipCountry: string = '';
    shipPostcode: string = '';
    postStreet: string = '';
    postCity: string = '';
    postState: string = '';
    postCountry: string = '';
    postPostcode: string = '';
    phone: string = '';
    fax: string = '';
    mobile: string = '';
    email: string = '';
    website: string = '';
    abn: string = '';
    remarks: string = '';
    adminNotes: string = '';
    bankBsb: string = '';
    bankAccountNo: string = '';
    bankName: string = '';
    eftBankRef: string = '';
    lodgementRef: string = '';
    revision: string = '';
    emails: string = '';
    phoneNumbers: string = '';
    addresses: string = '';
    externalRefId: string = '';
    discountDays: number = 0;
    creditLimit: number = 0;
    discountAmount: number = 0;
    showRunningTotals: boolean = false;
    shippingSameAsPost: boolean = false;
    isReseller: boolean = false;
    showInPos: boolean = false;
    lockDebtor: boolean = false;
    lockDiscounts: boolean = false;
    syncCounter: boolean = false;
    statement: number = 0;
    discountSyncCounter: boolean = false;
    orderOnMonday: boolean = false;
    orderOnTuesday: boolean = false;
    orderOnWednesday: boolean = false;
    orderOnThursday: boolean = false;
    orderOnFriday: boolean = false;
    orderOnSaturday: boolean = false;
    orderOnSunday: boolean = false;
    isSupplier: boolean = false;
    isCustomer: boolean = false;
    modTime: string = '';
    balances: Balances|null = null;
    extRefId: string = '';
    preventExport: boolean = false;
    dropShipping: boolean = false;
    terms: string = '';

    constructor(obj? : IAccount) {
        this.update(obj);
    }

    update(obj? : IAccount) {
        this.guid = obj && obj.guid || uuid();
        this.company = obj && obj.company || '';
        this.priceGroup = obj && obj.priceGroup || PriceGroup.Retail;
        this.accountCodeGuid = obj && obj.accountCodeGuid || '';
        this.branchGuid = obj && obj.branchGuid || '';
        this.resellerGuid = obj && obj.resellerGuid || '';
        this.defaultSalesPersonGuid = obj && obj.defaultSalesPersonGuid || '';
        this.defaultDeliveryRouteGuid = obj && obj.defaultDeliveryRouteGuid || '';
        this.refId = obj && obj.refId || '';
        this.firstName = obj && obj.firstName || '';
        this.lastName = obj && obj.lastName || '';
        this.shipStreet = obj && obj.shipStreet || '';
        this.shipCity = obj && obj.shipCity || '';
        this.shipState = obj && obj.shipState || '';
        this.shipCountry = obj && obj.shipCountry || '';
        this.shipPostcode = obj && obj.shipPostcode || '';
        this.postStreet = obj && obj.postStreet || '';
        this.postCity = obj && obj.postCity || '';
        this.postState = obj && obj.postState || '';
        this.postCountry = obj && obj.postCountry || '';
        this.postPostcode = obj && obj.postPostcode || '';
        this.phone = obj && obj.phone || '';
        this.fax = obj && obj.fax || '';
        this.mobile = obj && obj.mobile || '';
        this.email = obj && obj.email || '';
        this.website = obj && obj.website || '';
        this.abn = obj && obj.abn || '';
        this.remarks = obj && obj.remarks || '';
        this.adminNotes = obj && obj.adminNotes || '';
        this.bankBsb = obj && obj.bankBsb || '';
        this.bankAccountNo = obj && obj.bankAccountNo || '';
        this.bankName = obj && obj.bankName || '';
        this.eftBankRef = obj && obj.eftBankRef || '';
        this.lodgementRef = obj && obj.lodgementRef || '';
        this.revision = obj && obj.revision || '';
        this.emails = obj && obj.emails || '';
        this.phoneNumbers = obj && obj.phoneNumbers || '';
        this.addresses = obj && obj.addresses || '';
        // this.userName = obj && obj.userName || '';
        this.defaultCustomerGuid = obj && obj.defaultCustomerGuid || '';
        this.externalRefId = obj && obj.externalRefId || '';
        this.showRunningTotals = obj && obj.showRunningTotals || false;
        this.shippingSameAsPost = obj && obj.shippingSameAsPost || false;
        this.isReseller = obj && obj.isReseller || false;
        this.showInPos = obj && obj.showInPos || false;
        this.lockDebtor = obj && obj.lockDebtor || false;
        this.lockDiscounts = obj && obj.lockDiscounts || false;
        // this.syncInvoicesToWeb = obj && obj.syncInvoicesToWeb || false;
        this.syncCounter = obj && obj.syncCounter || false;
        this.statement = obj && obj.statement || 0.00;
        this.discountSyncCounter = obj && obj.discountSyncCounter || false;
        this.orderOnMonday = obj && obj.orderOnMonday || false;
        this.orderOnTuesday = obj && obj.orderOnTuesday || false;
        this.orderOnWednesday = obj && obj.orderOnWednesday || false;
        this.orderOnThursday = obj && obj.orderOnThursday || false;
        this.orderOnFriday = obj && obj.orderOnFriday || false;
        this.orderOnSaturday = obj && obj.orderOnSaturday || false;
        this.orderOnSunday = obj && obj.orderOnSunday || false;
        // this.isCasualContact = obj && obj.isCasualContact || false;
        this.isSupplier = obj && obj.isSupplier || false;
        this.isCustomer = obj && obj.isCustomer || false;
        this.modTime = obj && obj.modTime || new Date().toUTCString();
        this.extRefId = obj && obj.extRefId || '';
        this.preventExport = obj && obj.preventExport || false;
        this.dropShipping = obj && obj.dropShipping || false;
        this.terms = obj && obj.terms || '';

        if(this.isCustomer) {
            this.balances = new Balances(obj && obj.account_balances || {});
        } else {
            this.balances = new Balances(obj && obj.supplier_balances || {});
        }
    }
}
